list_captura_dados = [{'nome': 'hemacias', 'valorPR': '--', 'valoRA': '--', 'valorB': '--', 'unidade': '10⁶/mm³'},
                      {'nome': 'hemoglobina', 'valorPR': '--',
                          'valoRA': '--', 'valorB': '--', 'unidade': 'g/dl'},
                      {'nome': 'hematocrito', 'valorPR': '--', 'valoRA': '--',
                          'valorB': '--', 'unidade': '%'},
                      {'nome': 'vcm', 'valorPR': '--', 'valoRA': '--',
                          'valorB': '--', 'unidade': 'fl'},
                      {'nome': 'hcm', 'valorPR': '--', 'valoRA': '--',
                          'valorB': '--', 'unidade': 'pg'},
                      {'nome': 'chcm', 'valorPR': '--', 'valoRA': '--',
                          'valorB': '--', 'unidade': 'g/dl'},
                      {'nome': 'rdw', 'valorPR': '--', 'valoRA': '--',
                          'valorB': '--', 'unidade': '%'},
                      {'nome': 'leucocitos - global', 'valorPR': '--', 'valoRA': '--',
                          'valorB': '--', 'unidade': '/mm³'},
                      {'nome': 'neutrofilos bastonetes', 'valorPR': '--', 'mm3': '--', 'valoRA': '--',
                          'valorB': '--', 'unidade': '%'},
                      {'nome': 'neutrofilos segmentados', 'valorPR': '--', 'mm3': '--', 'valoRA': '--',
                          'valorB': '--', 'unidade': '%'},
                      {'nome': 'linfocitos', 'valorPR': '--', 'mm3': '--', 'valoRA': '--',
                          'valorB': '--', 'unidade': '%'},
                      {'nome': 'monocitos', 'valorPR': '--', 'mm3': '--', 'valoRA': '--',
                          'valorB': '--', 'unidade': '%'},
                      {'nome': 'eosinofilos', 'valorPR': '--', 'mm3': '--', 'valoRA': '--',
                          'valorB': '--', 'unidade': '%'},
                      {'nome': 'basafilos', 'valorPR': '--', 'mm3': '--', 'valoRA': '--',
                          'valorB': '--', 'unidade': '%'},
                      {'nome': 'plaquetas', 'valorPR': '--', 'valoRA': '--', 'valorB': '--', 'unidade': '/mm³'}]


lista_informacoes_buscada = ['hemacias',
                             'hemoglobina',
                             'hematocrito',
                             'vcm',
                             'hcm',
                             'chcm',
                             'rdw',
                             'leucocitos - global',
                             'neutrofilos bastonetes',
                             'neutrofilos segmentados',
                             'linfocitos',
                             'monocitos',
                             'eosinofilos',
                             'basafilos',
                             'plaquetas']
